version: "3.8"

services:
  api:
    container_name: agentpilot_evo_ae991c2e_api
    image: atendai/evolution-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evo:evo@postgres:5432/evolution
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379
      - AUTHENTICATION_API_KEY=okok

  postgres:
    container_name: agentpilot_evo_ae991c2e_pg
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=evo
      - POSTGRES_PASSWORD=evo
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: agentpilot_evo_ae991c2e_redis
    image: redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
